spring.application.name=albumy

spring.datasource.url=jdbc:postgresql://localhost:5432/albumy
spring.datasource.username=postgres
spring.datasource.password=azerty
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

upload.dir=uploads

jwt.secret=albumy-secret-key-for-jwt-token-generation-must-be-long-enough-for-hs256
jwt.expiration=86400000

server.port=8080
